###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: infrastructure-manager
  name: infrastructure-manager
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: infrastructure-manager
  template:
    metadata:
      labels:
        cluster: management
        component: infrastructure-manager
    spec:
      containers:
      - name: infrastructure-manager
        image: nalejregistry.azurecr.io/nalej/infrastructure-manager:VERSION
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.nalej:8800"
        - "--installerAddress=installer.nalej:8900"
        - "--tempDir=/tmp/nalej"
        volumeMounts:
        - name: temp-dir
          mountPath: "/tmp/nalej"
        securityContext:
          runAsUser: 2000
      volumes:
      - name: temp-dir
        emptyDir: {}
      imagePullSecrets:
      - name: nalej-registry
