###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: infrastructure-manager
  name: infrastructure-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: infrastructure-manager
  template:
    metadata:
      labels:
        cluster: management
        component: infrastructure-manager
    spec:
      containers:
      - name: infrastructure-manager
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/infrastructure-manager:__NPH_VERSION
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
        - "--installerAddress=installer.__NPH_NAMESPACE:8900"
        - "--tempDir=/tmp/nalej"
        - "--queueAddress=broker.__NPH_NAMESPACE:6650"
        volumeMounts:
        - name: temp-dir
          mountPath: "/tmp/nalej"
        securityContext:
          runAsUser: 2000
      volumes:
      - name: temp-dir
        emptyDir: {}
      imagePullSecrets:
      - name: nalej-registry
